# Generated by Django 4.1.2 on 2022-10-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='electronic.category'),
        ),
    ]
