# Generated by Django 4.1.2 on 2022-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0003_electronic_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='electronic'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
