# Generated by Django 4.1.2 on 2022-10-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0004_alter_category_name'),
        ('electronic', '0004_electronic_img_alter_category_name'),
    ]

    operations = [
    ]
